// generated by "sampctl package init"
#include <a_samp>
#include <streamer>
#include <strlib>

#include "blackboard.inc"

main()
{
	CreateBlackboard(-1763.696777, 796.1, 160.85, 0.000000, 0.000000, -90.0, .worldid = 31, .interiorid = 0);
}

/*
hook OnPlayerEnterBlackboard(playerid, boardid)
{
	ShowInfoBox(playerid, "Puoi interagire con la lavagna scrivendo nella chat", 3000);
	return 1;
}

hook OnPlayerExitBlackboard(playerid, boardid)
{
	HideInfoBox(playerid);
	return 1;
}
*/